# Generated by Django 2.2.2 on 2020-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200608_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('commited', 'commited'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='flag',
            field=models.CharField(blank=True, choices=[('Raciest', 'Raciest'), ('Abusing', 'Abusing')], max_length=20, null=True),
        ),
    ]
