# Generated by Django 2.2.2 on 2020-06-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200609_1817'),
        ('social', '0003_auto_20200609_1516'),
    ]

    operations = [
    ]
